const dummyFlights = [
  {
    id: 1,
    name: "Indigo",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.7000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 2,
    name: "Jet Airways",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.9000",
    date: "2023-05-20",
    time: "2:30 PM",
    image: "flight2.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Spice Jet",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.13000",
    date: "2023-05-22",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Spice Jet",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.9000",
    date: "2023-05-22",
    time: "5:00 PM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Indigo",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.12000",
    date: "2023-05-22",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Air India",
    origin: "Mumbai",
    destination: "Bangalore",
    fare: "Rs.7000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Indigo",
    origin: "Kolkata",
    destination: "Pune",
    fare: "Rs.8000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Spice Jet",
    origin: "Kolkata",
    destination: "Patna",
    fare: "Rs.4500",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Spice Jet",
    origin: "Mumbai",
    destination: "Bangalore",
    fare: "Rs.5000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Vistara",
    origin: "Delhi",
    destination: "Bangalore",
    fare: "Rs.9000",
    date: "2023-05-21",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "1D", available: true },
      { id: "1E", available: true },
      { id: "1F", available: false },
      { id: "1G", available: true },
      { id: "2A", available: true },
      { id: "2C", available: false },
      { id: "3A", available: true },
      { id: "4B", available: true },
      { id: "5C", available: false },
    ],
  },
  {
    id: 1,
    name: "Vistara",
    origin: "Delhi",
    destination: "Pune",
    fare: "Rs.8000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "2A", available: true },
      { id: "3B", available: true },
      { id: "2C", available: false },
      { id: "5A", available: true },
      { id: "6B", available: true },
      { id: "7C", available: false },
    ],
  },
  {
    id: 1,
    name: "Akasha Airlines",
    origin: "Delhi",
    destination: "Patna",
    fare: "Rs.8000",
    date: "2023-05-20",
    time: "10:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "2A", available: true },
      { id: "3B", available: true },
      { id: "2C", available: false },
      { id: "5A", available: true },
      { id: "6B", available: true },
      { id: "7C", available: false },
    ],
  },
  {
    id: 1,
    name: "Akasha Airlines",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.7000",
    date: "2023-05-21",
    time: "12:00 AM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "2A", available: true },
      { id: "3B", available: true },
      { id: "2C", available: false },
      { id: "5A", available: true },
      { id: "6B", available: true },
      { id: "7C", available: false },
    ],
  },
  {
    id: 1,
    name: "Air Asia",
    origin: "Kolkata",
    destination: "Bangalore",
    fare: "Rs.8000",
    date: "2023-05-21",
    time: "8:00 PM",
    image: "flight1.jpg",
    seats: [
      { id: "1A", available: true },
      { id: "1B", available: true },
      { id: "1C", available: false },
      { id: "2A", available: true },
      { id: "3B", available: true },
      { id: "2C", available: false },
      { id: "5A", available: true },
      { id: "6B", available: true },
      { id: "7C", available: false },
    ],
  },
];

export default dummyFlights;